# Generated by Django 5.2 on 2025-04-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='popis',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='dokonceno',
            new_name='resolved',
        ),
        migrations.AddField(
            model_name='task',
            name='priorita',
            field=models.CharField(choices=[('height', 'Height'), ('middle', 'Middle'), ('low', 'Low')], default='stredni', max_length=10),
        ),
    ]
