# Generated by Django 5.2 on 2025-04-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_rename_popis_task_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priorita',
            new_name='priority',
        ),
    ]
